---
- name: reboot system
  reboot:
    reboot_timeout: 300
  become: true

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: restart kubernetes-goat-portforward
  systemd:
    name: kubernetes-goat-portforward
    state: restarted
  become: true