---
- name: Export kubeconfig from KIND
  command: kind export kubeconfig --name {{ kind_cluster_name }}
  become: true

- name: Check kubectl contexts
  command: kubectl config get-contexts
  register: kubectl_contexts
  become: true
  failed_when: false

- name: Display available contexts
  debug:
    msg: "{{ kubectl_contexts.stdout_lines }}"

- name: Test cluster access
  command: kubectl cluster-info
  register: cluster_info
  become: true
  failed_when: false

- name: Display cluster info
  debug:
    msg: "{{ cluster_info.stdout_lines }}"