---
- name: Create KIND config directory
  file:
    path: /opt/kind
    state: directory
    mode: '0755'
  become: true

- name: Generate KIND cluster configuration
  template:
    src: kind-cluster.yaml.j2
    dest: /opt/kind/cluster.yaml
    mode: '0644'
  become: true

- name: Check if KIND cluster exists
  command: kind get clusters
  register: existing_clusters
  changed_when: false
  failed_when: false

- name: Create KIND cluster
  command: kind create cluster --name {{ kind_cluster_name }} --config /opt/kind/cluster.yaml
  when: kind_cluster_name not in existing_clusters.stdout
  register: cluster_creation
  become: true

- name: Ensure .kube directory exists for ansible user
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Get kubeconfig from KIND
  command: kind get kubeconfig --name {{ kind_cluster_name }}
  register: kind_kubeconfig
  become: true

- name: Write kubeconfig to ansible user's .kube/config
  copy:
    content: "{{ kind_kubeconfig.stdout }}"
    dest: /home/{{ ansible_user }}/.kube/config
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Wait for cluster to be ready
  command: kubectl cluster-info
  register: cluster_info
  until: cluster_info.rc == 0
  retries: 30
  delay: 10
  become: true

- name: Verify cluster is running
  command: kubectl get nodes
  register: cluster_nodes
  changed_when: false
  become: true

- name: Display cluster status
  debug:
    msg: "Cluster nodes: {{ cluster_nodes.stdout_lines }}"