---
- name: Clone Kubernetes Goat repository
  git:
    repo: "{{ kubernetes_goat_repo }}"
    dest: "{{ kubernetes_goat_path }}"
    version: "{{ kubernetes_goat_version }}"
    force: yes
  become: true

- name: Set ownership of Kubernetes Goat directory
  file:
    path: "{{ kubernetes_goat_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
  become: true

- name: Make setup script executable
  file:
    path: "{{ kubernetes_goat_path }}/setup-kubernetes-goat.sh"
    mode: '0755'

- name: Deploy Kubernetes Goat
  shell: |
    cd {{ kubernetes_goat_path }}
    ./setup-kubernetes-goat.sh
  environment:
    KUBECONFIG: /root/.kube/config
  register: goat_deployment
  become: true
  failed_when: goat_deployment.rc != 0

- name: Display Kubernetes Goat setup errors if any
  debug:
    msg: "Setup errors: {{ goat_deployment.stderr_lines }}"
  when: goat_deployment.stderr_lines is defined and goat_deployment.stderr_lines | length > 0