---
- name: Set password for ansible user
  user:
    name: "{{ ansible_user }}"
    password: "{{ '1234' | password_hash('sha512') }}"
    update_password: always
  become: true

- name: Ensure SSH service is running
  service:
    name: ssh
    state: started
    enabled: true
  become: true

- name: Configure SSH to allow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
  become: true
  notify: restart ssh

- name: Ensure PubkeyAuthentication is not disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present
  become: true
  notify: restart ssh

- name: Restart SSH service to apply changes
  service:
    name: ssh
    state: restarted
  become: true

- name: Display SSH login information
  debug:
    msg: 
      - "SSH access has been configured!"
      - "Username: {{ ansible_user }}"
      - "Password: 1234"
      - "You can now SSH into this machine using: ssh {{ ansible_user }}@{{ ansible_host | default(inventory_hostname) }}"