---
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: restart kubernetes-goat-portforward
  systemd:
    name: kubernetes-goat-portforward
    state: restarted
  become: true

- name: restart ssh
  service:
    name: ssh
    state: restarted
  become: true